--[[--
THIS LITTLE UTILITY HELPS YOU KEEP YOUR PLACE
ASSIGN IT TO A HOTKEY. I USE NUMPAD *
PRESS THE HOTKEY. IT DROPS A MARKER.
SCROLL SOMEWHERE ELSE IN YOUR PROJECT, CLICK AROUND.
PRESS THE HOTKEY AGAIN. IT DROPS A MARKER *AND THEN* JUMPS YOU BACK TO THE PREVIOUS MARKER'S LOCATION.
USEFUL FOR GRABBING BITS AND PIECES FROM OTHER PARTS OF YOUR PROJECT WITHOUT LOSING YOUR PLACE.

THIS MAKES USE OF THE FACT THAT USER-PLACED MARKERS TYPICALLY START AT 1 FOR SOME REASON. THEY MIGHT CHANGE THAT IN THE FUTURE.
THIS USES MARKER INDEX 0, WHICH SHOULD BE UNUSED UNLESS YOU DID IT MANUALLY (OR, AGAIN, THEY CHANGE SOMETHING IN THE FUTURE).
JUST MAKE SURE MARKER INDEX 0 IS FREE.
--]]--

-- get cursor position

cursorPos = reaper.GetCursorPosition()

-- check for marker

reaper.GoToMarker(0,0,false)
placeMarker = reaper.SetProjectMarker(0,false,cursorPos,0,"<")

if placeMarker then
  return
else
  placeMarker = reaper.AddProjectMarker(0,false,cursorPos,0,"<",0)
end